### ISSUE TITLE
知识管理以输出为主

### ISSUE THREAD

**Issue by Rebecca19** [Rebecca19/Rebecca19.github.io#1]
上周日听了闪闪的讲演，我悄悄和她说讲得真棒，她对我笑笑，“那你输出一篇文章吧。”所以我敲出了这篇文章。
# 无法输出？可能“姿势”不对

身处信息爆炸时代，自己还算相对好学，每天汲取信息量是不小，可我总觉得在输出上存在困难。往往我总以为自己输入还是不够，现在想来是知识管理思维出了问题。

首先，存储知识，一味汲取而不加整理。周末翻看有道笔记（以前喜欢在这里面存东西），会发现犹如一个巨大的垃圾桶，比如我浏览到大二时写得张爱玲《流言》的读后感，自己却完全想不起来曾经写了这种东西。

再者，自己在输出之时，有完美主义者倾向，总觉得自己准备不够好，所以非常不愿意输出，某种意义上造成了拖延。

从这两者来看，实质我是思维模式上存在误区：给自己定了较高的目标，而又不懂得拆解开来做。闪闪在演讲里提到很核心的一点，知识管理，以输出为主。无论你输出了什么，做总是比不做要好。无论你给自己定的目标有多高，你总要一点点练习以接近。

听完演讲，我回来看了阳志平的《人生标准九》，其中两句话让我触动很深，第一句是“70分的人生，若有70分的把握就去做，一边做一边修正。”凡事觉得有7成把握就可以动手去做，做完之后我们还可以慢慢修正，下次定会做得更好。很多事情，自己常常瞻前顾后，反而会失去良机，不断尝试，不断进步，可能是更快的一种方法。

第二句是“社会上永远存在着一个‘人比人’的问题。我们不会因为自己的愚蠢而悲伤，只会因为比周围的人更蠢而痛苦。”我们不停地要求自己其实是希望自己可以做得比别人好，这确实是有颗向上的心，但是我们在比较的时候，一定要为自己选取一个合适的目标，不要过低也不要过高，同时应该调整自己的心态，不是为了比而比，更多的是寻找一种参照。
# 看知识管理的正确“姿势”

既然说知识管理，以输出为主，那么选择一个正确的输出姿势则很重要。

知识的层级容量，卡片<文章<书。故而我们在输出之时，可以先从难度最低、消耗工作记忆最少的卡片开始，而不是一上来上来就逼迫自己形成文章。一休和武士比赛做年糕时，一休是一点一点磨糯米粉的。而武士一上来便开始搅拌所有糯米粉，看似比一休快，其实有很多糯米粉没拌开，在最后输给一休。

值得一提的是，文章不单只文字，也可以是演讲、图片等形式；同理，书/项目只是相对成体系、复杂度高的一套认知的代名词，可以是书、项目、培训等等。

提到卡片，阳志平的博客中提到纳博科夫和钱钟书非常喜欢记录卡片。自己很喜欢看钱钟书的文章，尤其是那本《写在人生的边上》那本散文集。在读钱老的书之时，自己深深为他简洁的文风和超大的容量所震撼，往往一片短小的散文背后牵连着几十个著名的作品或典故，你却丝毫不觉得累赘或冗长。

阳志平的博客中也解释了为什么优秀的作家喜欢用卡片？一是容易记忆阅读心得，二是写作时能增加创意密度，三是修改时容易远距离联想。所以平时整合知识，第一个层级是卡片，卡片积累多了，分类存储，以后才能为文章所用。
# 可能是比较高效的工具

闪闪推荐了她自己平时知识输出的工具，我个人觉得很好，但思量了一下，还是用了可能，因为我觉得道理是相同的，而在工具选择这件事上，确实各有各的好，适合自己才最重要。她推荐了：印象笔记+workflowy+markdown+github。

我自己其实会用的是有道笔记+workflowy+markdown，所以重点谈下这几个。

无论是有道还是印象笔记还是其它什么，这步的软件用途在于下载资料。很多人喜欢把他们当做整理软件，而且他们也确实将它们理得很清楚。但对于一些人比如我来说，这种软件用久了就像一个垃圾桶，根本不会花很多精力去打理，所以将它们作为一个存储软件是合适的。我们可以在其它软件上，实现卡片输出，比如workflowy。

闪闪同时演示了几款卡片工具，说实话，我自己最喜欢workflowy。它的设计原理就是以输出为主而非输入，同时它还支持云存储和全文检索的功能。我觉得它好像一整张无限延伸可折叠的大白纸，我可以无限的增加列表，根据需要我也可以把它们随时折叠起来。

workflowy可以当做卡片工具，进行碎片化输出，但是这绝对不是终点，知识输出是为了能用，大部分时候写文章是一个很好的方式，那么好的写作工具必不可少。闪闪推荐了markdown文法的软件，我自己其实也在用这样的软件，自己用的是Mod，一款Mac上的免费APP。markdown文法带一些简易的编程符号，基本上扫一眼说明书即可使用，它的好处是，免去了你排版的煎熬，很多规则已经制定好了，你只需要敲敲键盘，全身心写作就可以了。

github自己目前还没涉足编程这个领域，希望今年能有机会开启吧。

最后还是要非常感谢闪闪的推荐，自己真心觉得workflowy这个应用简直是完美呀，可以存储一切，按标签搜索一切，拯救了我这个不会用印象笔记的人。而且我觉得其实无论使用怎么样的工具并不重要，而在于自己的思维方式和想象力的应用。

**Comment by ishanshan** [comment]
哈哈 @Rebecca19 说输出文章真的输出了，还加了很多自己实践后的感受想法，好棒！

>github自己目前还没涉足编程这个领域，希望今年能有机会开启吧。

不仅编程，很多领域都可以用到 GitHub 这个可供性强大的工具哦。其版本控制功能可以省去很多编辑、创作的麻烦，分布式存储则非常方便协作。强烈推荐尽快玩起~且要加入开智团队， GitHub 需要尽快上手哦：P

>真心觉得workflowy这个应用简直是完美呀，可以存储一切，按标签搜索一切

标签是违反人类认知习惯的，大脑习惯树状，但标签是云…… 
若非特定场景，比如了解整体与局部，在 WorkFlowy 中建议少用标签，因为标签会越用越多，越多越乱=-=找东西，全文检索功能就能满足大部分需求了~
